var names = {
  female: [
    "Tilda Sweatin",
    "Katherine Rugburn",
    "Audrey Rugburn",
    "Meryl Streaks",
    "Vivian Lay",
    "Kathy 'bates",
    "Faye Runaway",
    "Glenn Closer",
    "Kate Winslut",
    "Mary Steamvirgin",
    "Anna Can Dick",
    "Imogen Toots",
    "Hillary Skank",
    "Cherry Ontop",
    "Emma Boned",
    "Natalie Porkman",
    "Sandra Bullcock",
    "Carrie Fishsmell",
    "Jane Fondle",
    "Diane Cheatin'",
    "Adrienne Barboned",
    "Michelle Pfluffer",
    "Helena Bangem Carter",
    "Fapke Janssen",
    "Jamie Lee Beef Curtains",
    "Annette Boning",
    "Bette Diddler",
    "Peepee Neuwirth",
    "Lorraine Cocko",
    "Holly Humper",
    "Anne Bangcroft",
    "Anne Hathawang",
    "SigHorny Weaver",
    "Anna Packed In",
    "Julia Knobberts"
  ],
  male: [
    "Alan Thicc",
    "Benedict Cumbersomebatch",
    "Blowin' Atkinson",
    "Clint Morningwood",
    "Channing TaintYum",
    "Colin Filth",
    "Dustin Boffman",
    'Dwayne "The Cock" Johnson',
    "Gape Vagoda",
    "Gerard Butt",
    "Giovanni Ribbedisi",
    "Going Downey, Jr",
    "Gregory Pecker",
    "Jake Fillin All",
    "James Gandalf Weenie",
    "Keith Gayvid",
    "Kevin Spanky",
    "Idris Elbowdeep",
    "Jack Lemmon Party",
    "Paul Blewman",
    "Power O'Toole",
    "Phillip Seemore Buffmen",
    "Robert Splattinson",
    "Russell Blowe",
    "Seann William Slutt",
    "Tom Diddleson",
    "Tom Spanks",
  ]
};