// jshint -W098
// jshint -W117

var names = {
  female: [
    "Tilda Sweatin",
    "Katherine Rugburn",
    "Audrey Rugburn",
    "Meryl Streaks",
    "Vivian Lay",
    "Kathy 'bates",
    "Faye Runaway",
    "Glenn Closer",
    "Kate Winslut",
    "Mary Steamvirgin",
    "Anna Can Dick",
    "Imogen Toots",
    "Hillary Skank",
    "Cherry Ontop",
    "Emma Boned",
    "Natalie Porkman",
    "Sandra Bullcock",
    "Carrie Fishsmell",
    "Jane Fondle",
    "Diane Cheatin'",
    "Adrienne Barboned",
    "Michelle Pfluffer",
    "Helena Bangem Carter",
    "Fapke Janssen",
    "Jamie Lee Beef Curtains",
    "Annette Boning",
    "Bette Diddler",
    "Peepee Neuwirth",
    "Lorraine Cocko",
    "Holly Humper",
    "Anne Bangcroft",
    "Anne Hathawang",
    "SigHorny Weaver",
    "Anna Packed In"
  ],
  male: [
    "Keith Gayvid",
    "James Gandalf Weenie",
    "Giovanni Ribbedisi",
    "Jake Fillin All",
    "Gerard Butt",
    "Clint Morningwood",
    "Channing TaintYum",
    "Colin Filth",
    "Dustin Boffman",
    "Benedict Cumbersomebatch",
    "Kevin Spanky",
    "Going Downey, Jr",
    "Tom Spanks",
    "Paul Blewman",
    "Jack Lemmon Party",
    "Power O'Toole",
    "Phillip SeeMore BuffMen",
    "Gregory Pecker"
  ]
};