const names = {
  female: [
    'Adrienne Barboned',
    'Anna Can Dick',
    'Anna Packed In',
    'Annal Gunge',
    'Anne Bangcroft',
    'Anne Hathawang',
    'Annette Boning',
    'Audrey Rugburn',
    'Bette Diddler',
    'Carrie Fishsmell',
    "Diane Cheatin'",
    'Emma Boned',
    'Fapke Janssen',
    'Faye Runaway',
    'Glenn Closer',
    'Helena Bangem Carter',
    'Hillary Skank',
    'Holly Humper',
    'Imogen Toots',
    'Jamie Lee Beef Curtains',
    'Jane Fondle',
    'Julia Knobberts',
    'Kate Winslut',
    'Katherine Rugburn',
    "Kathy 'bates",
    'Lorraine Cocko',
    'Mary Steamvirgin',
    'Meryl Streaks',
    'Michelle Pfluffer',
    'Natalie Porkman',
    'Peepee Neuwirth',
    'Rhea See Horny',
    'Sandra Bullcock',
    'SigHorny Weaver',
    'Tilda Sweatin',
    'Vivian Lay'
  ],
  male: [
    "Aarod Pull",
    "Alan Thicc",
    "Benedict Cumbersomebatch",
    "Blowin' Atkinson",
    "Bryan Crammston",
    "Bob Oldekink",
    "Clint Morningwood",
    "Channing TaintYum",
    "Colin Filth",
    "Dustin Boffman",
    'Dwayne “The Cock” Johnson',
    'Ed Semgma, Jr.',
    "Gape Vagoda",
    "Gerard Butt",
    "Giancarlo Espesemen-o",
    "Giovanni Ribbedisi",
    "Going Downey, Jr",
    "Gregory Pecker",
    "Huge Jack, Man",
    "Jake Fillin All",
    "James Gandalf Weenie",
    "Johnathan Bonks",
    "Keith Gayvid",
    "Kevin Spanky",
    "Idris Elbowdeep",
    "Jack Lemmon Party",
    "Loose Willis",
    "Michael DickKeen",
    "Paul Blewman",
    "Power O'Toole",
    "Phillip Seemore Buffmen",
    "Robert Splattinson",
    "Russell Blowe",
    "Seann William Slutt",
    "Tom Diddleson",
    "Tom Spanks",
  ]
};