const music = {
  bands: [
    "Aphex Twink",
    "Asstodong",
    "Belle Biv, Da Ho",
    "Boyz N2 Men",
    "Deep In The Purple",
    "Frank Fappa and the Mothers I'd Like To Fuck Of Invention",
    "Hall In Oates",
    "Hüsky Düdes",
    "Insane Clown Pussy",
    "Jethro Tug",
    "Megadepth",
    "Nipplez With Attitude",
    "Pink Oyster Cult",
    "Poundgarden",
    "Pryx",
    "Red Hot Chubby Peckers",
    "Rub The Jewels",
    "Snatchbox Plenty",
    "The Bobbing Heads",
    "The Vulve Pipe",
    "The White Splotches",
    "Urethamics",
    "VD On The Radio"
  ],
  singers: [
    "Aesoft Cock",
    "Danny Jelqman",
    "Del Tha Funkee Homo",
    "Dick Assley",
    "GEI$HA",
    "Ice Pube",
    "Jon Boner Jovi",
    "Lady Gagger",
    "Licki Mivaj",
    "Mick Jacker",
    "Nail'er Swift"
  ]
};