const music = {
  bands: [
    "Aphex Twink",
    "Asstodong",
    "Belle Biv, Da Ho",
    "Boyz N2 Men",
    "Deep In The Purple",
    "Hall In Oates",
    "Hüsky Düdes",
    "Jethro Tug",
    "Megadepth",
    "Nipplez With Attitude",
    "Pink Oyster Cult",
    "Poundgarden",
    "Pryx",
    "Red Hot Chubby Peckers",
    "Rub The Jewels",
    "Snatchbox Plenty",
    "The Bobbing Heads",
    "The Vulve Pipe",
    "The White Splotches",
    "Urethamics",
    "VD On The Radio"
  ],
  singers: [
    "Aesoft Cock",
    "Danny Jelqman",
    "Del Tha Funkee Homo",
    "Dick Assley",
    "Frank Fappa",
    "GEI$HA",
    "Ice Pube",
    "Jon Boner Jovi",
    "Lady Gagger",
    "Licki Mivaj",
    "Mick Jacker",
    "Nail'er Swift",
    "Shagging 2 Dope and Violent JO"
  ]
};