// jshint -W098
var pornTitles = [
  "'bating For Godot",
  "12 Years A Slut",
  "19″ 17″",
  "2 Fast 2 Furry Puss",
  "21 Pumps, SKEET!",
  "28 Cocks Later",
  "3 Men And A Jar Of Lube",
  "50 Fist Dates",
  "9″ to 5″",
  "A Boy And His Dong",
  "A Clockwork Orgy",
  "A Dogging's Purpose",
  "A Queer and Pleasant Stranger",
  "A Streetwalker Named Desire&eacute;",
  "A Tail And Two Titties",
  "Abbot and Costello Fuck The Mummy",
  "Adventures In Face Sitting",
  "Alexander and the Terrible, Horrible, No Good, Very Bad Handjob",
  "All We Imagine Is Tight",
  "Alvin and the Fuckmunks 2: The Fuckuel",
  "American History XXX",
  "American Fanfiction",
  "An American Werewolf In Laura",
  "An Officer With A Gentleman",
  "Anne of Groin Gobbles",
  "Are You There? Oh God! It's Pee, Margaret.",
  "As You Lick It",
  "Ass Onion",
  "Assassin's Cream",
  "Astroglide Boy",
  "Atlas Chugged",
  "Attack The Cock",
  "Babe: Piss In The City",
  "BALL-E",
  "Balls of Furry",
  "Bang My Bum Slowly",
  "Banging John Malkovich",
  "Bareback To The Future",
  "Beavis And Butt-Head Do Each Other",
  "Before The Devil Knows You're Dicked",
  "Being Inside Elmo",
  "Bend Over, Like Beckham",
  "Beth Becomes Horny",
  "Bicurious George",
  "Big Hero 16″",
  "Big Trouble in Little Vagina",
  "Bio-Domme",
  "Birdman (or The Unexpected Pleasure of Dominance)",
  "Bite Club",
  "Black Booty",
  "Black In Men",
  "Black Poon Rising",
  "Blowing For Columbine",
  "Blumpkinhead",
  "Boobs! A Madea Porno",
  "Bottom Gun",
  "Boyz N The Clitoral Hood",
  "Breakfast In Tiffany",
  "Breasts In Shows",
  "Brian's Schlong",
  "Bright Lights, Big Titties",
  "Catch Me If You Cum",
  "CitizenWhore",
  "Clitty Lickers 2: The Legend of Curly Pubes",
  "Cool Handjob, Luke",
  "Crotch-22",
  "Cum With Dick and Jane",
  "Cum and Cummer",
  "Cum And See",
  "Cumhog Millionaire",
  "Das Booty",
  "Depth of a Salesman",
  "Despicable Pee",
  "Detective Peek-At-You",
  "The Dickson Experimental Sounding Film",
  "Dirty/Hairy",
  "Dog Dick Afternoon",
  "Don't Tell Mom The Babysitter's Giving Head",
  "Dong: Skullfuck Island",
  "Dr. Strangelust, or: How I Learned To Stop Worrying And Love The Bum",
  "Drilling Zoe",
  "Drive Horny",
  "Driving Into Ms Daisy",
  "Eight Pegged Freaks",
  "Eliot Ness and his Uncuckables",
  "Ender's Gay",
  "Enemy of the Prostate",
  "Erin Cock-A-Bitch",
  "Even Reverse Cowgirls Get the Blues",
  "Everyone In Her, All At Once",
  "Evil Head 2: Head By Dawn",
  "FUX 1138",
  "Fannie Hall",
  "Fantastic Breasts And Where To Fuck Them",
  "Fantastic Fucks, Mister",
  "Fast Times In Bridgette's Thighs",
  "Ferris Bueller Jerks Off",
  "Fingering Dory",
  "Fist Fist, Bang Bang",
  "Fist Me Deadly",
  "Fitting It In",
  "Seven Years In To Beth",
  "Forest Humps",
  "Four Weddings, A Funeral, And Then A Gangbang",
  "Free Dildos Outside of Tribbing, Missouri",
  "Frotting Hill",
  "Fuck Everlasting",
  "Fuck-It Ralph",
  "Full Metal Dildo",
  "G*A*S*H",
  "G.I. Joe: Masturbation",
  "Gash of the Titans",
  "Gays of Thunder",
  "Get Off",
  "Ghost In Michelle",
  "GladHeAteHer",
  "Glazed and Confused",
  "Glen, Garry, Glenn, Ross, and Six Other Guys",
  "Godzilla Minus Cum",
  "God's Not Het",
  "Good Night And Good Fuck",
  "GoodFellatas",
  "Gooper Troopers",
  "Gosford Porking",
  "Group Sex on the Bounty",
  "Guardians Of That Gal's Ass, Vol. 3",
  "Guess Who Came During Dinner",
  "Gunfight at the KY Corral",
  "Hannah on Her Sisters",
  "Harold & Kumar Fuck In A White Castle Bathroom",
  "Hello, Real Dolly!",
  "Homo Alone 2: Lust In New York",
  "Horton Spears A Dude",
  "How To Drain Your Dragon",
  "How To Get Some Head In Advertising",
  "Humpin' Jack Flash",
  "Humpy Old Men",
  "I Am Clam",
  "I Broke My Back Mounting",
  "I'm In Her, With Andre",
  "The Impregnation of Jessie James By The Cuckhold Robert Ford",
  "In Sid Anus",
  "In The Cumpanties of Men",
  "Invasion of the Bawdy Snatches",
  "Isle of PAWGs",
  "Jack Reacharound",
  "Jacob's Splatter",
  "Jiro Creams On Suki",
  "Jiz and the Diaphragms",
  "Judge Headd",
  "Kneel And Deliver",
  "Koyaanistwatsi",
  "Kubo and the G Strings",
  "Lady In The Water Closet",
  "Lapdancer In The Dark",
  "Lawrence of a Labia",
  "Le Voyage Sans La Lube",
  "Let the White One In",
  "Logan Lucky Fucky Sucky",
  "Lube²: Hyperlube",
  "M69GAN",
  "Mad Maxxx: Furious Roadhead",
  "“Manos”: The Handjobs of Fate",
  "Me, Myself in Irene",
  "Mega Low Dong",
  "Midnight Ladyboy",
  "Million Dollar Booby",
  "Missionary? Impossible!",
  "Moanal",
  "Moneyballin",
  "Monsters' Pink",
  "Morning Gloryhole",
  "Mother!Fucker!",
  "Motion Impossible",
  "Mr. Chode's Wild Ride",
  "Mr. Popper's Poppers",
  "Mr. Smith Goes Down on Washington",
  "Much Ado About Cumming",
  "My Big Fat Freak, Wetting",
  "My Sex Life With A Zucchini",
  "Never Been Kissed... There",
  "Night At The Mapplethorpe Museum",
  "Night of the Giving Head",
  "Nightballer",
  "Nookie of the Year",
  "Nutbusters",
  "Nutting Butt Trouble",
  "Ocean's 11″",
  "Oiledboy",
  "On Her Majesty's Secret Cervix",  
  "One Blew Over The Cuckold's Nest",
  "Only Orgies In The Building",
  "Operation Jumbo Cock",
  "Oppenhummer",
  "Pacific Rimjob",
  "Pan's Labiarinth",
  "Pearl Necklace Harbor",
  "Pee Wee's Big Member",
  "Peggy Guggenheim: Fart Addict",
  "Penetrating Howard's End",
  "Pies Like Us",
  "Pissmaster",
  "Play With Misty For Me",
  "Poonlight",
  "Poonrise Kingdom",
  "Poonstruck",
  "Pride and Prejudice and Prostitutes",
  "Public Enemas",
  "Puppet Masturbator",
  "Queen of the Dental Dam",
  "Queefer Madness",
  "Raging Balls",
  "Ready? Play With Oneself",
  "Rebel Without a Cooze",
  "Replicunt",
  "Risky Jizness",
  "Robocuck",
  "Rogerin' Me",
  "Rosemary's Babymaker",
  "Rosencrantz and Guildenstern Are Giving Head",
  "Rub, Lola! Rub!",
  "SLC Spunk",
  "Saturday Night Beaver",
  "Scatatouille",
  "Scott Pilgrim Vs Those Girls",
  "Sex Machina",
  "Shaun The Creep Movie",
  "Shaving Mr. Banks",
  "Shaving Ryan's Priates",
  "Short Cummings",
  "Sinning In The Rain",
  "Six Days Seven Cocks",
  "Slop Shot",
  "Slutter Island",
  "Some Like A Twat",
  "Something Dicked This Way Cums",
  "Sore Jaws",
  "Sorry To Bugger You",
  "Space Jammin'",
  "Stanford's Prisonsex Experiments",
  "Stay Hard 2: Stay Harder",
  "Step-Sister Act 2: Bareback Is A Habit",
  "Stephen King's Tit",
  "Steve's Jobs",
  "Stop! Or My Mom Will Squirt",
  "Straight Into Conner",
  "Stroke Dracula, Bram",
  "Suicide Squat",
  "Supersize Meat",
  "Take This Knob And Shove It",
  "Tetsuo: The Erect Man",
  "The African Drag Queen",
  "The Angry Black Girl And Her Monster Sized Dildo",
  "The Assventures of Fuckaroo Buttzai Across The Gape Dimension",
  "The Bear Up There",
  "The Bicycle Queef",
  "The Big Stick",
  "The Black Swanzstucker",
  "The Boner Collector",
  "The Boy Shorts",
  "The Ladyboys From Brazil",
  "The Color of a Money Shot",
  "The Cum of All Fears",
  "The Cumshot Heard 'Round The World",
  "The Constant Groper",
  "The Curious Case of Benjamin's Butthole",
  "The Dark Bros In: Fuck Soup",
  "The Day His Girth Stood Still",
  "The Devil Wears Nada",
  "The Eggplant Emoji Movie",
  "The Englishman Who Went Up A Hill And Came On My Mountains",
  "The Fabulous Bukkake Boys",
  "The Fantastic Foursome",
  "The Fast And The Bi-Curious",
  "The Filth Element",
  "The First Slammed Hunk",
  "The Flesh",
  "The Grinch Whose Hole Fits Fists",
  "The Gropes of Wrath",
  "The Ho Men",
  "The Hump For Red October",
  "The Incredible Mr. Limpdick",
  "The Indian In The Cuckhold",
  "The Italian Blowjob",
  "The Just Ass League",
  "The Last Starfucker",
  "The Legend of Gagger Vance",
  "The Licker Man",
  "The Lust Boys",
  "The Lust Unicorn",
  "The Lust of the Mohicans",
  "The Magnificent Semen",
  "The Maltese Fistin",
  "The Man Who Was Thirstaaayy 🥵",
  "The Mud Wrestler",
  "The Munchurian Candidass",
  "The Emptied Man",
  "The Nutting Professor",
  "The Outlaw Josie's Holes",
  "The Pleasure of Sierra's Madre",
  "The Power of the Doggystyle",
  "The Princess Ride",
  "The Scissorhood of the Traveling Underpants",
  "The Squirt Locker",
  "The Stepfather, Part II",
  "The Tight Stuff",
  "The Unbearable Tightness of Ian",
  "The Usual Cuck Sex",
  "The Wolf of Ball Street",
  "There Will Be Cum",
  "There's Someone Inside Mary",
  "Thighs Wide Shut",
  "Thirst Man",
  "This Ain't Lars von Trier's Nymphomaniac XXX",
  "Thong of the South",
  "Throbbin' Hood: Princess of Queefs",
  "Tim, Fuck Two",
  "Tinker, Tailor, Soldier, Spycam",
  "Titty Titty Gang Bang",
  "Titzcarraldo",
  "To Shave and Shave Not",
  "Training Gay",
  "Trans Formers 2: Revenge of the Ballin'",
  "Trick 'r Skeet",
  "Tub Girl Time Machine",
  "Twatman vs Booberman: Dawn of Just Tits",
  "Twerking Girl",
  "Under The Cum Cum Tree",
  "Urethral Weapon",
  "Veinspotting",
  "Vulva! Lez Vegas",
  "Wally Wanko and the Chocolate Fucktory",
  "Wangs of New York",
  "Wank You For Smoking",
  "Watersportsworld",
  "Wet Dreams May Come",
  "Wet Hot American Hummer",
  "What In The World Are You Spraying (An Alex Jones Documentary)",
  "Where In The World Is Carmen Sandiego's Clitoris?",
  "While You Were Peeping",
  "Whiskey, Tango, Facefuck",
  "White Men Can't Hump",
  "Who Rogered That Rabbit?",
  "Whore-a! Whore-a! Whore-a!",
  "Who'd We Do In The Shadows",
  "Wyatt Slurp",
  "XXX: State of the Union: XXX",
  "Yes Bears",
  "You've Got Male",
  
  // DOCUMENTARIES **********************************************
  "An Incontinent Truth",
  "Jodorowsky's Poon",

  // COEN BROTHERS **********************************************
  "Pud Simple",
  // Crimewave???
  "Glazing Arizona",
  "Filler's Crossing",
  "Bart On Twink",
  "The Cocksucker Proxy",
  "Fargoo",
  "The Big Lebow Chicka Wow Wow Ski",
  "O Rubber, Where Art Thou?",
  "The Man Who Was In There",
  "Intolerable Chastity",
  "The Ladydrillers",
  "No Cunt Free For Old Men",
  "Burn After Peeing",
  // A Serious Man??
  "True Clit",
  "Gambutt",
  "Actually Inside Llewyn Davis",
  "Nail Caesar!",
  // Suburbicon???
  "The Ballad Of Buster Nutt",

  // INDIANA JONES ***********************************************
  "Indiana Bones and the Last Cruised Gay",
  "Indiana Bones and the Rammers of Lusty Mark",
  "Indiana Bones and the Temple of Poon",
  "Indiana Bones and Krystal's Skullfuck",

  // ALFRED HITCHCOCK *******************************************
  "Rear Entry Widow",
  "Spurtigo",
  "Mr. and Mrs. Smith (But She's His Stepmom They Just Coincidentally Have the Same Last Name)",
  "Dial M For Muffdiving",
  "To Catch a Queef",
  "The Man Who Blew Too Much",
  "Slobbertage",
  "Psych, Ho",
  "Strangers on a Tranny",
  "Da Birds, Mate",
  
  // QUENTIN TARANTINO ******************************************
  "Reservoir Dongs",
  "Natural Porn Killers",
  "Fill Bill, vol 2",
  "In Glory Hole Basterds",
  "Django Chained",

  // MIYAZAKI ***************************************************
  "My Neighbor Frotoro",
  "Kiki's Rimjobbery Service",
  // Princess Mononoke??
  "Spurted Away",
  "Howl's Moving Asshole",
  // Ponyo

  // JOHN WOO ***************************************************
  "A Wetter Tomorrow",
  "Hard Femboiled",
  "Bulleit And Some Head",
  "Face/Fuck",

  // MEL BROOKS *************************************************
  "Hung Frankenstein",
  "Rubbin' Hood: Men In Tight Men",
  "The Jism Producers",
  "Dracula: Cucked and Loving It",

  // LORD OF THE RINGS ******************************************
  "Lord of the Cockrings: The Fellowship of the Cockring",
  "Lord of the Cockrings: The Return of the Kink",
  "Lord of the Cockrings: The Two Showers",
  
  // HARRY POTTER ***********************************************
  "Hairy Twatter and the Pornographer's Bone",
  "Hairy Twatter and the Chamber of Secretions",
  "Hairy Twatter and the Prisoner of Ass Cabin",
  "Hairy Twatter and the Gobblin' of Your Spire",
  "Hairy Twatter and the Order of the Three Dicks",
  "Hairy Twatter and the Half Chub Prince",
  "Hairy Twatter and the Depth He Swallows",
  
  // THE HUNGER GAMES *******************************************
  "The Hung Games",
  "The Hung Games: Flashing Firecrotch",
  "The Hung Games: Crotch On Fire",
  "The Hung Games: Mocking J/O [Part 1]",
  
  // JAMES BOND ************************************************
  "Dr. O Yes",
  "Thunderballs",
  "Fuck Russians With Love",
  "On Her Majesty's Secret Cervix",
  "Octopussy, Novempussy, Decapussy... Whatapussy!",
  "Goldfingering",
  "Try Another Gay",
  "The Man With The Golden Cunt",
  
  // STAR TREK ************************************************
  "Slut Trek II: The Wrath of Cum",
  "Slut Trek III: The Search For Cock",
  "Slut Trek IV: The Voyeur's Moan",
  "Slut Trek V: The Final Cunt's Here",
  "Slut Trek VI: The Undiscovered Entry",
  "Slut Trek: Penetrations",
  "Slut Trek: Fist Contact",

  // STAR WARS ************************************************
  "Star Whores: The Foreskin Awakens",
  "Star Whores: The Last JOI",
  
  // TV SHOWS *************************************************
  "30″ Cock",
  "A Bit of Fry in Laurie",
  "America's Next Topless Model",
  "Battlethroat Glackglickgluck",
  "Better Ball Saul",
  "Beverly's Hills, Billy!",
  "BoJack Horsedong",
  "Boy Meat's World",
  "Breaking Chad",
  "Charles In Charles",
  "Eastbound And Going Down",
  "Jane, The “Virgin”",
  "Joanie Loves Crotchie",
  "Joe Pera Talks You Off",
  "Leave It In My Beaver",
  "Married... With An Understanding",
  "Nathan For Everyone",
  "Perfect Strange",
  "Person of Incest",
  "Pokémoan",
  "Slut Trek: Deep Throat 9",
  "Spoo Detective",
  "That Mitchell & Webb Nookie",
  "The End of the World, Fucking",
  "The Gang Bang Theory",
  "The Goop Place",
  "The Handmaid's Tail",
  "The John From Cincinnati",
  "Twins Peeking",
  "We're Always Horny In Philadelphia",
  "Welcome Back, Frotteur",
  "Who's The Bottom?",
  "Whose Hole Is It Anyway?",
  "Piss Angel: MILFFREAK",
  "Moral Oral",

  // NETFLIX ****************************************************
  "Haters Whack Off!",
  "Strangers' Things",
  "Marvel's Jessica Bones",
  "Unbelievably Fuckable Kimmy Schmidt",
  "Grace and Spankie",
  "Wet Hot American Hummer: Ten Beers Later",
  "Everyone Sucks!",
  "Russian Real Doll",
  "Salt, Fat, Acid, Skeet!",
  "Somebody Fill Phil",
  "Wild Wild Cunt, See?",
  "Knock Up The Spouse",
  "Making A Murderer Cum",
  "Orgy Is The New Black",
  "The Queef's Gambit",
  
  // MUSICALS ***************************************************
  "Taint Must Be Shaven",
  "Anything Grows",
  "MILF Saigon",
  "Diddler on the Roof",
  "Man of La Muncha",
  "Arse Nick and Yo Face",
  "Guys and Blow Up Dolls",
  "Clamilton",
  "Bring in 'da Boys, Bring in 'da Spunk",
  "Scats",
  "Moulan Spooge",
  "Annie Got That Cum",
  "Spermalot",
  "All That Jizz",
  "Miserable Lezzies",
  "Fist Me, Kate",
  "The Drag King And I",
  "Grease'd",
  "Stepmomenschanz",
  "Seven Brides For A Brother",
  "Fishnet Stockings",
  "Gentlemen Prefer Bald",
  "Bye Bye Virginity",
  "No Literally I Mean It, ANYTHING Goes",
  "Cornholeval",
  "How To Give Her The Business Without Really Trying",
  "My Fair Labia",
  
  // PLAYS ******************************************************
  "On Speed And Plowin",
  "Sex and Sexability",
  "King Lear",
  
  // BOOKS ******************************************************
  "A Wrinkle In Tom",
  "Journey To The Center With His Girth",
  "I Have No Muff And I Must Cream",
  "A Supposedly Fun Thing We're Get Paid To Do Again",
  "Stepdaughterhouse 5",
  "Cat's F/F Cradle",
  "Blowers For Algerdong",
  "The Old Man And The Pee",
  
  // PODCASTS ***************************************************
  "My Brother, My Brother In Me"
];
