// jshint -W098
var pornTitles = [
  "'bating For Godot",
  "12 Years A Slut",
  "19″ 17″",
  "2 Fast 2 Furry Puss",
  "21 Pumps, SKEET!",
  "28 Cocks Later",
  "3 Men And A Jar Of Lube",
  "50 Fist Dates",
  "9″ to 5″",
  "A Boy And His Dong",
  "A Clockwork Orgy",
  "A Dogging's Purpose",
  "A Queer and Pleasant Stranger",
  "A Streetwalker Named Desire&eacute;",
  "A Tail And Two Titties",
  "Abbot and Costello Fuck The Mummy",
  "Adventures In Face Sitting",
  "Alexander and the Terrible, Horrible, No Good, Very Bad Handjob",
  "Alvin and the Fuckmunks 2: The Fuckuel",
  "American History XXX",
  "An American Warewolf In Laura",
  "An Officer With A Gentleman",
  "Anne of Groin Gobbles",
  "As You Lick It",
  "Assassin's Cream",
  "Astroglide Boy",
  "Atlas Chugged",
  "Attack The Cock",
  "BALL-E",
  "Balls of Furry",
  "Bang My Bum Slowly",
  "Banging John Malkovich",
  "Bareback To The Future",
  "Before The Devil Knows You're Dicked",
  "Being Inside Elmo",
  "Bend Over, Like Beckham",
  "Bicurious George",
  "Big Hero 16″",
  "Big Trouble in Little Vagina",
  "Bio-Domme",
  "Birdman (or The Unexpected Pleasure of Dominance)",
  "Bite Club",
  "Black Booty",
  "Black In Men",
  "Blowing For Columbine",
  "Blumpkinhead",
  "Boobs! A Madea Porno",
  "Boyz N The Clitoral Hood",
  "Breakfast In Tiffany",
  "Breasts In Shows",
  "Brian's Schlong",
  "Bright Lights, Big Titties",
  "CitizenWhore",
  "Clitty Lickers 2: The Legend of Curly Pubes",
  "Cool Handjob, Luke",
  "Crotch-22",
  "Cum With Dick and Jane",
  "Cum and Cummer",
  "Cumhog Millionaire",
  "Das Booty",
  "Depth of a Salesman",
  "Despicable Pee",
  "Detective Peek-At-You",
  "Dirty/Hairy",
  "Dog Dick Afternoon",
  "Don't Tell Mom The Babysitter's Giving Head",
  "Dong: Skullfuck Island",
  "Dr. Strangelust, or: How I Learned To Stop Worrying And Love The Bum",
  "Drilling Zoe",
  "Driving Into Ms Daisy",
  "Ender's Gay",
  "Enemy of the Prostate",
  "Erin Cock-A-Bitch",
  "Even Reverse Cowgirls Get the Blues",
  "Evil Head 2: Head By Dawn",
  "FUX 1138",
  "Face/Fuck",
  "Fannie Hall",
  "Fantastic Breasts And Where To Fuck Them",
  "Fantastic Fucks, Mister",
  "Fast Times In Bridgette's Thighs",
  "Ferris Bueller Jerks Off",
  "Fingering Dory",
  "Fist Fist, Bang Bang",
  "Fist Me Deadly",
  "Five Years In To Beth",
  "Four Weddings, A Funeral, And Then A Gangbang",
  "Free Dildos Outside of Tribbing, Missouri",
  "Frotting Hill",
  "Fuck Everlasting",
  "Fuck-It Ralph",
  "Full Metal Dildo",
  "G*A*S*H",
  "G.I. Joe: Masturbation",
  "Gash of the Titans",
  "Gays of Thunder",
  "Get Off",
  "Ghost In Michelle",
  "GladHeAteHer",
  "Glazed and Confused",
  "Glen, Garry, Glenn, Ross, and Six Other Guys",
  "God's Not Het",
  "Good Night And Good Fuck",
  "GoodFellatas",
  "Gosford Porking",
  "Group Sex on the Bounty",
  "Guess Who Came On Dinner",
  "Gunfight at the KY Corral",
  "Hannah on Her Sisters",
  "Harold & Kumar Fuck In A White Castle Bathroom",
  "Hello, Real Dolly!",
  "Homo Alone 2: Lust In New York",
  "Horton Spears A Dude",
  "How To Drain Your Dragon",
  "How To Get Some Head In Advertising",
  "Humpin' Jack Flash",
  "I Am Clam",
  "I Broke My Back Mounting",
  "I'm In Her, With Andre",
  "In Sid Anus",
  "In The Cumpanties of Men",
  "Indiana Bones and the Temple of Poon",
  "Invasion of the Bawdy Snatches",
  "Jack Reacharound",
  "Jacob's Splatter",
  "Jiro Creams On Suki",
  "Jiz and the Diaphragms",
  "Judge Headd",
  "Kneel And Deliver",
  "Koyaanistwatsi",
  "Kubo and the G Strings",
  "Lady In The Water Closet",
  "Lapdancer In The Dark",
  "Lawrence of a Labia",
  "Le Voyage Sans La Lube",
  "Let the White One In",
  "Logan Lucky Fucky Sucky",
  "Lube²: Hyperlube",
  "Mad Maxxx: Furious Loads",
  "Me, Myself in Irene",
  "Mega Low Dong",
  "Midnight Ladyboy",
  "Million Dollar Booby",
  "Missionary? Impossible!",
  "Moanal",
  "Moneyballin",
  "Monsters' Pink",
  "Morning Gloryhole",
  "Mother!Fucker!",
  "Motion Impossible",
  "Mr. Chode's Wild Ride",
  "Mr. Popper's Poppers",
  "Mr. Smith Goes Down on Washington",
  "Much Ado About Cumming",
  "My Big Fat Freak, Wetting",
  "My Sex Life With A Zucchini",
  "Natural Porn Killers",
  "Never Been Kissed... There",
  "Night At The Mapplethorpe Museum",
  "Night of the Giving Head",
  "Nightballer",
  "Nookie of the Year",
  "Nutbusters",
  "Nutting Butt Trouble",
  "Ocean's 11″",
  "Oiledboy",
  "On Her Majesty's Secret Cervix",
  "One Blew Over The Cuckold's Nest",
  "Pacific Rimjob",
  "Pan's Labiarinth",
  "Pearl Necklace Harbor",
  "Pee Wee's Big Member",
  "Peggy Guggenheim: Fart Addict",
  "Penetrating Howard's End",
  "Pies Like Us",
  "Pissmaster",
  "Play With Misty For Me",
  "Poonlight",
  "Poonrise Kingdom",
  "Poonstruck",
  "Pride and Prejudice and Prostitutes",
  "Public Enemas",
  "Puppet Masturbator",
  "Queen of the Dental Dam",
  "Raging Balls",
  "Ready? Play With Oneself",
  "Rear Entry Widow",
  "Rebel Without a Cooze",
  "Replicunt",
  "Risky Jizness",
  "Robocuck",
  "Rogerin' Me",
  "Rosemary's Babymaker",
  "Rosencrantz and Guildenstern Are Giving Head",
  "Rub, Lola! Rub!",
  "SLC Spunk",
  "Saturday Night Beaver",
  "Scatatouille",
  "Scott Pilgrim Vs Those Girls",
  "Sex Machina",
  "Shaun The Creep Movie",
  "Shaving Mr. Banks",
  "Shaving Ryan's Priates",
  "Sinning In The Rain",
  "Six Days Seven Cocks",
  "Slop Shot",
  "Slutter Island",
  "Sore Jaws",
  "Sorry To Bugger You",
  "Space Jammin'",
  "Spurtigo",
  "Stanford's Prisonsex Experiments",
  "Stay Hard 2: Stay Harder",
  "Step-Sister Act 2: Bareback Is A Habit",
  "Stephen King's Tit",
  "Steve's Jobs",
  "Stop! Or My Mom Will Squirt",
  "Straight Into Conner",
  "Strangers on a Tranny",
  "Stroke Dracula, Bram",
  "Suicide Squat",
  "Supersize Meat",
  "Take This Knob And Shove It",
  "Tetsuo: The Erect Man",
  "The African Drag Queen",
  "The Assventures of Fuckaroo Buttzai Across The Gape Dimension",
  "The Bear Up There",
  "The Bicycle Queef",
  "The Big Stick",
  "The Black Swanzstucker",
  "The Boner Collector",
  "The Boy Shorts",
  "The Ladyboys From Brazil",
  "The Color of a Money Shot",
  "The Constant Groper",
  "The Curious Case of Benjamin's Butthole",
  "The Dark Bros In: Fuck Soup",
  "The Day His Girth Stood Still",
  "The Devil Wears Nada",
  "The Eggplant Emoji Movie",
  "The Englishman Who Went Up A Hill And Came On My Mountains",
  "The Fabulous Bukkake Boys",
  "The Fantastic Foursome",
  "The Fast And The Bi-Curious",
  "The Filth Element",
  "The Grinch Whose Hole Fits Fists",
  "The Gropes of Wrath",
  "The Ho Men",
  "The Hump For Red October",
  "The Incredible Mr. Limpdick",
  "The Indian In The Cuckhold",
  "The Italian Blowjob",
  "The Just Ass League",
  "The Last Starfucker",
  "The Legend of Gagger Vance",
  "The Licker Man",
  "The Lust Boys",
  "The Lust Unicorn",
  "The Lust of the Mohicans",
  "The Magnificent Semen",
  "The Maltese Fistin",
  "The Mud Wrestler",
  "The Munchurian Candidass",
  "The Nutting Professor",
  "The Pleasure of Sierra's Madre",
  "The Princess Ride",
  "The Scissorhood of the Traveling Underpants",
  "The Squirt Locker",
  "The Stepfather, Part II",
  "The Tight Stuff",
  "The Unbearable Tightness of Ian",
  "The Usual Cuck Sex",
  "The Wolf of Ball Street",
  "There Will Be Cum",
  "There's Someone Inside Mary",
  "Thighs Wide Shut",
  "Thirst Man",
  "This Ain't Lars von Trier's Nymphomaniac XXX",
  "Throbbin' Hood: Princess of Queefs",
  "Tim, Fuck Two",
  "Tinker, Tailor, Soldier, Spycam",
  "Titty Titty Gang Bang",
  "Titzcarraldo",
  "To Shave and Shave Not",
  "Training Gay",
  "Trans Formers 2: Revenge of the Ballin'",
  "Trick 'r Skeet",
  "Tub Girl Time Machine",
  "Twatman vs Booberman: Dawn of Just Tits",
  "Twerking Girl",
  "Urethral Weapon",
  "Veinspotting",
  "Vulva! Lez Vegas",
  "Wangs of New York",
  "Wank You For Smoking",
  "Watersportsworld",
  "Wet Dreams May Come",
  "Wet Hot American Hummer",
  "What In The World Are You Spraying (An Alex Jones Documentary)",
  "Where In The World Is Carmen Sandiego's Clitoris?",
  "While You Were Peeping",
  "Whiskey, Tango, Facefuck",
  "White Men Can't Hump",
  "Who Rogered That Rabbit?",
  "Who'd We Do In The Shadows",
  "Wyatt Slurp",
  "XXX: State of the Union: XXX",
  "You've Got Male",
  "“Manos”: The Handjobs of Fate",
  
  // Documentaries
  "An Incontinent Truth",
  "Jodorowsky's Poon",
  
  // Jack Lemmon
  "Some Like A Twat",
  "Humpy Old Men",
  "Under The Cum Cum Tree",
  
  ///////////////////////////////////////
  // These are all Coen Brothers movies
  "Pud Simple",
  // Crimewave???
  "Glazing Arizona",
  "Filler's Crossing",
  "Bart On Twink",
  "The Cocksucker Proxy",
  // Fargo???
  "The Big Lebow Chicka Wow Wow Ski",
  "O Rubber, Where Art Thou?",
  "The Man Who Was In There",
  // Intolerable Cruelty???
  "The Ladydrillers",
  "No Cunt Free For Old Men",
  "Burn After Peeing",
  // A Serious Man??
  "True Clit",
  // Gambit??
  "Actually Inside Llewyn Davis",
  "Nail Caesar!",
  // Suburbicon???
  "The Ballad Of Buster Nutt",
  
  
  // Quentin Tarantino
  "In Glory Hole Basterds",
  "Django Chained",
  "Fill Bill, vol 2",
  "Reservoir Dongs",
  "Jack Me Brown",
  
  // Lord of the Rings series
  "Lord of the Cockrings: The Fellowship of the Cockring",
  "Lord of the Cockrings: The Return of the Kink",
  "Lord of the Cockrings: The Two Showers",
  
  // The Harry Potter Series
  "Hairy Twatter and the Pornographer's Bone",
  "Hairy Twatter and the Chamber of Secretions",
  "Hairy Twatter and the Prisoner of Ass Cabin",
  "Hairy Twatter and the Gobblin' of Your Spire",
  "Hairy Twatter and the Order of the Three Dicks",
  "Hairy Twatter and the Half Chub Prince",
  "Hairy Twatter and the Depth He Swallows",
  
  // The Hunger Games
  "The Hung Games",
  "The Hung Games: Flashing Firecrotch",
  "The Hung Games: Crotch On Fire",
  "The Hung Games: Mocking J/O [Part 1]",
  
  // James Bond
  "Dr. O Yes",
  "Thunderballs",
  "Fuck Russians With Love",
  "On Her Majesty's Secret Cervix",
  "Octopussy, Novempussy, Decapussy... Whatapussy!",
  "Goldfingering",
  "Try Another Gay",
  "The Man With The Golden Cunt",
  
  // Star Trek series...
  "Slut Trek II: The Wrath of Cum",
  "Slut Trek III: The Search For Cock",
  "Slut Trek IV: The Voyeur's Moan",
  "Slut Trek V: The Final Cunt's Here",
  "Slut Trek VI: The Undiscovered Entry",
  "Slut Trek: Penetrations",
  "Slut Trek: Fist Contact",

  // Star Wars
  "Star Whores: The Foreskin Awakens",
  "Star Whores: The Last JOI",
  
  // These are all TV shows....
  "30″ Cock",
  "A Bit of Fry in Laurie",
  "America's Next Topless Model",
  "Better Ball Saul",
  "Beverly's Hills, Billy!",
  "BoJack Horsedong",
  "Boy Meat's World",
  "Breaking Chad",
  "Charles In Charles",
  "Eastbound And Going Down",
  "Jane, The “Virgin”",
  "Joanie Loves Crotchie",
  "Joe Pera Talks You Off",
  "Married... With An Understanding",
  "Nathan For Everyone",
  "Perfect Strange",
  "Person of Incest",
  "Pokémoan",
  "Slut Trek: Deep Throat 9",
  "Spoo Detective",
  "The End of the World, Fucking",
  "The Gang Bang Theory",
  "The Goop Place",
  "The Handmaid's Tail",
  "The John From Cincinnati",
  "Twins Peeking",
  "Welcome Back, Frotteur",
  "Who's The Bottom?",

  // Netflix
  "Haters Whack Off!",
  "Strangers' Things",
  "Marvel's Jessica Bones",
  "Unbelievably Fuckable Kimmy Schmidt",
  "Grace and Spankie",
  "Wet Hot American Hummer: Ten Beers Later",
  "Everyone Sucks!",
  "Russian Real Doll",
  "Salt, Fat, Acid, Skeet!",
  "Somebody Fill Phil",
  "Wild Wild Cunt, See?",
  "Knock Up The Spouse",
  "Making A Murderer Cum",
  "Orgy Is The New Black",
  
  // Musicals...
  "Taint Must Be Shaven",
  "Anything Grows",
  "MILF Saigon",
  "Diddler on the Roof",
  "Man of La Muncha",
  "Arse Nick and Yo Face",
  "Guys and Blow Up Dolls",
  "Clamilton",
  "Bring in 'da Boys, Bring in 'da Spunk",
  "Scats",
  "Moulan Spooge",
  "Annie Got That Cum",
  "Spermalot",
  "All That Jizz",
  "Miserable Lezzies",
  "Fist Me, Kate",
  "The Drag King And I",
  "Grease'd",
  "Stepmomenschanz",
  "Seven Brides For A Brother",
  "Fishnet Stockings",
  "Gentlemen Prefer Bald",
  "Bye Bye Virginity",
  "No Literally I Mean It, ANYTHING Goes",
  "Cornholeval",
  "How To Give Her The Business Without Really Trying",
  "My Fair Labia",
  
  // Plays
  "On Speed And Plowin",
  
  // Books
  "A Wrinkle In Tom",
  "Journey To The Center With His Girth",
  "I Have No Muff And I Must Cream",
  "A Supposedly Fun Thing We're Get Paid To Do Again",
  
  // PODCASTS
  "My Brother, My Brother In Me"
];
